steps:
  - name: node:14
    entrypoint: npm
    args: ["ci"]

  - name: node:14
    entrypoint: npm
    args: ["run", "build", "--", "--configuration=production"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "Contenido de dist/ledgerly-front:"
        ls -l dist/ledgerly-front || echo "⚠️ No se generó la carpeta"
        echo "Subiendo a bucket..."
        gsutil -m rsync -r dist/ledgerly-front gs://$_BUCKET_NAME

substitutions:
  _BUCKET_NAME: "ledgerly-frontend-bucket"

options:
  logging: CLOUD_LOGGING_ONLY
